name: build-release

on:
  push:
    branches:
      - main

jobs:
  build-executables:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Install ldid
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v4
        with:
          repository: 'one-click-studio/one-click-os'
          ref: '9-proper-v1'
          token: ${{ secrets.GH_TOKEN }}
          path: 'one-click-os'

      # move to the directory where the package.json is located
      - name: Move to package.json directory
        run: cd ./one-click-os/crates/audio-manager-node

      - name: read package.json version
        uses: Saionaro/extract-package-version@v1.2.1
        id: package-json

      - name: Install npm dependencies
        run: npm install

      - name: Upload executables to asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          draft: ${{ github.ref == 'refs/heads/main' }}
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          tag_name: ${{ steps.package-json.outputs.version }}
          files: |
             ./*.node
